// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MHWildsArmour.Json;
//
//    var armorSeriesDatum = ArmorSeriesDatum.FromJson(jsonString);

namespace MHWildsArmour.Json
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ArmorSeriesDatum
    {
        [JsonProperty("_Index", NullValueHandling = NullValueHandling.Ignore)]
        public long? Index { get; set; }

        [JsonProperty("_Series", NullValueHandling = NullValueHandling.Ignore)]
        public string Series { get; set; }

        [JsonProperty("_Name", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? NameGuid { get; set; }

        [JsonProperty("_ModelVariety", NullValueHandling = NullValueHandling.Ignore)]
        public string ModelVariety { get; set; }

        [JsonProperty("_ModId", NullValueHandling = NullValueHandling.Ignore)]
        public long? ModId { get; set; }

        [JsonProperty("_ModSubMaleId", NullValueHandling = NullValueHandling.Ignore)]
        public long? ModSubMaleId { get; set; }

        [JsonProperty("_ModSubFemaleId", NullValueHandling = NullValueHandling.Ignore)]
        public long? ModSubFemaleId { get; set; }

        [JsonProperty("_SortId", NullValueHandling = NullValueHandling.Ignore)]
        public long? SortId { get; set; }

        [JsonProperty("_Rare", NullValueHandling = NullValueHandling.Ignore)]
        public string RareString { get; set; }

        [JsonProperty("_Price", NullValueHandling = NullValueHandling.Ignore)]
        public long? Price { get; set; }

        [JsonProperty("_Color", NullValueHandling = NullValueHandling.Ignore)]
        public string Color { get; set; }
    }

    public partial class ArmorSeriesDatum
    {
        public string Name { get; set; }

        public int Rare { get; set; }

        public int MaxLevel { get; set; }

        public int DefPerLevel { get; set; }

        public static ArmorSeriesDatum[] FromJson(string json) => JsonConvert.DeserializeObject<ArmorSeriesDatum[]>(json, MHWildsArmour.Json.ArmorSeriesConverter.Settings);
    }

    public static partial class Serialize
    {
        public static string ToJson(this ArmorSeriesDatum[] self) => JsonConvert.SerializeObject(self, MHWildsArmour.Json.ArmorSeriesConverter.Settings);
    }

    internal static class ArmorSeriesConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
