// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MHWildsArmour.Json;
//
//    var armorTranscendRecipeDatum = ArmorTranscendRecipeDatum.FromJson(jsonString);

namespace MHWildsArmour.Json
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ArmorTranscendRecipeDatum
    {
        [JsonProperty("_Index", NullValueHandling = NullValueHandling.Ignore)]
        public long? Index { get; set; }

        [JsonProperty("_SeriesId", NullValueHandling = NullValueHandling.Ignore)]
        public string SeriesId { get; set; }

        [JsonProperty("_Item", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Item { get; set; }

        [JsonProperty("_ItemNum", NullValueHandling = NullValueHandling.Ignore)]
        public List<long> ItemNum { get; set; }
    }

    public partial class ArmorTranscendRecipeDatum
    {
        public ItemDatum[] Items { get; set; }

        public static List<ArmorTranscendRecipeDatum> FromJson(string json) => JsonConvert.DeserializeObject<List<ArmorTranscendRecipeDatum>>(json, MHWildsArmour.Json.Converter.Settings);
    }

    public static partial class Serialize
    {
        public static string ToJson(this List<ArmorTranscendRecipeDatum> self) => JsonConvert.SerializeObject(self, MHWildsArmour.Json.Converter.Settings);
    }

    internal static class ArmorTranscendRecipeConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
