// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MHWildsArmour.Json;
//
//    var armorSetWikiDb = ArmorSetWikiDb.FromJson(jsonString);

namespace MHWildsArmour.Json
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using MediawikiTranslator.Models.ArmorSets;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ArmorSetWikiDb
    {
        [JsonProperty("Order")]
        public long Order { get; set; }

        [JsonProperty("SetName")]
        public string SetName { get; set; }

        [JsonProperty("Game")]
        public string Game { get; set; }

        [JsonProperty("MaleFrontImg")]
        public string MaleFrontImg { get; set; }

        [JsonProperty("MaleBackImg")]
        public string MaleBackImg { get; set; }

        [JsonProperty("FemaleFrontImg")]
        public string FemaleFrontImg { get; set; }

        [JsonProperty("FemaleBackImg")]
        public string FemaleBackImg { get; set; }

        [JsonProperty("SetSkill1Name")]
        public string SetSkill1Name { get; set; }

        [JsonProperty("SetSkill2Name")]
        public object SetSkill2Name { get; set; }

        [JsonProperty("GroupSkill1Name")]
        public string GroupSkill1Name { get; set; }

        [JsonProperty("GroupSkill2Name")]
        public object GroupSkill2Name { get; set; }

        [JsonProperty("Rarity")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Rarity { get; set; }

        [JsonProperty("Pieces")]
        public List<ArmorPieceWikiDb> Pieces { get; set; }
    }

    public partial class ArmorPieceWikiDb
    {
        [JsonProperty("Skills")]
        public List<ArmorSkillWikiDb> Skills { get; set; }

        [JsonProperty("Materials")]
        public List<ArmorMaterialWikiDb> Materials { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Rarity")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Rarity { get; set; }

        [JsonProperty("ForgingCost")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ForgingCost { get; set; }

        [JsonProperty("IconType")]
        public string IconType { get; set; }

        [JsonProperty("MaleImage")]
        public string MaleImage { get; set; }

        [JsonProperty("FemaleImage")]
        public string FemaleImage { get; set; }

        [JsonProperty("Description")]
        public string Description { get; set; }

        [JsonProperty("Defense")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Defense { get; set; }

        [JsonProperty("MaxDefense")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long MaxDefense { get; set; }

        [JsonProperty("FireRes")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long FireRes { get; set; }

        [JsonProperty("WaterRes")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long WaterRes { get; set; }

        [JsonProperty("ThunderRes")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ThunderRes { get; set; }

        [JsonProperty("IceRes")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long IceRes { get; set; }

        [JsonProperty("DragonRes")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long DragonRes { get; set; }

        [JsonProperty("Decos1")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Decos1 { get; set; }

        [JsonProperty("Decos2")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Decos2 { get; set; }

        [JsonProperty("Decos3")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Decos3 { get; set; }

        [JsonProperty("Decos4")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Decos4 { get; set; }
    }

    public partial class ArmorMaterialWikiDb
    {
        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Quantity")]
        public long Quantity { get; set; }
    }

    public partial class ArmorSkillWikiDb
    {
        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Level")]
        public long Level { get; set; }
    }

    public partial class ArmorSetWikiDb
    {
        public static ArmorSetWikiDb FromJson(string json) => JsonConvert.DeserializeObject<ArmorSetWikiDb>(json, MHWildsArmour.Json.Converter.Settings);
    }

    public static partial class Serialize
    {
        public static string ToJson(this ArmorSetWikiDb self) => JsonConvert.SerializeObject(self, MHWildsArmour.Json.Converter.Settings);

        public static string ToJson(this List<ArmorSetWikiDb> self) => JsonConvert.SerializeObject(self, MHWildsArmour.Json.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
            Formatting = Formatting.Indented
        };
    }

    internal class ArmorSetWikiDbParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ArmorSetWikiDbParseStringConverter Singleton = new ArmorSetWikiDbParseStringConverter();
    }
}
