// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MHWildsArmour.Json;
//
//    var armorTranscendCostDatum = ArmorTranscendCostDatum.FromJson(jsonString);

namespace MHWildsArmour.Json
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ArmorTranscendCostDatum
    {
        [JsonProperty("_Index", NullValueHandling = NullValueHandling.Ignore)]
        public long? Index { get; set; }

        [JsonProperty("_Rare", NullValueHandling = NullValueHandling.Ignore)]
        public string Rare { get; set; }

        [JsonProperty("_Cost", NullValueHandling = NullValueHandling.Ignore)]
        public long? Cost { get; set; }
    }

    public partial class ArmorTranscendCostDatum
    {
        public static List<ArmorTranscendCostDatum> FromJson(string json) => JsonConvert.DeserializeObject<List<ArmorTranscendCostDatum>>(json, MHWildsArmour.Json.Converter.Settings);
    }

    public static partial class Serialize
    {
        public static string ToJson(this List<ArmorTranscendCostDatum> self) => JsonConvert.SerializeObject(self, MHWildsArmour.Json.Converter.Settings);
    }

    internal static class ArmorTranscendCostDatumConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
