// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MHWildsArmour.Json;
//
//    var armorSkill = ArmorSkill.FromJson(jsonString);

namespace MHWildsArmour.Json
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ArmorSkill
    {
        [JsonProperty("_Index", NullValueHandling = NullValueHandling.Ignore)]
        public long? Index { get; set; }

        [JsonProperty("_skillId", NullValueHandling = NullValueHandling.Ignore)]
        public string SkillId { get; set; }

        [JsonProperty("_skillType", NullValueHandling = NullValueHandling.Ignore)]
        public string SkillType { get; set; }

        [JsonProperty("_skillCategory", NullValueHandling = NullValueHandling.Ignore)]
        public string SkillCategory { get; set; }

        [JsonProperty("_SkillIconType", NullValueHandling = NullValueHandling.Ignore)]
        public string SkillIconType { get; set; }

        [JsonProperty("_skillName", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? SkillName { get; set; }

        [JsonProperty("_skillExplain", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? SkillExplain { get; set; }

        [JsonProperty("_SortId", NullValueHandling = NullValueHandling.Ignore)]
        public long? SortId { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("explain", NullValueHandling = NullValueHandling.Ignore)]
        public string Explain { get; set; }

        [JsonProperty("skillLevels", NullValueHandling = NullValueHandling.Ignore)]
        public SkillLevel[] SkillLevels { get; set; }
    }

    public partial class SkillLevel
    {
        [JsonProperty("level", NullValueHandling = NullValueHandling.Ignore)]
        public long? Level { get; set; }

        [JsonProperty("explain", NullValueHandling = NullValueHandling.Ignore)]
        public string Explain { get; set; }
    }

    public partial class ArmorSkill
    {
        public static ArmorSkill[] FromJson(string json) => JsonConvert.DeserializeObject<ArmorSkill[]>(json, MHWildsArmour.Json.ArmorSkillConverter.Settings);
    }

    public static partial class Serialize
    {
        public static string ToJson(this ArmorSkill[] self) => JsonConvert.SerializeObject(self, MHWildsArmour.Json.ArmorSkillConverter.Settings);
    }

    internal static class ArmorSkillConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
