// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MHWildsArmour.Json;
//
//    var armorUpgradeDatum = ArmorUpgradeDatum.FromJson(jsonString);

namespace MHWildsArmour.Json
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ArmorUpgradeDatum
    {
        [JsonProperty("_Index", NullValueHandling = NullValueHandling.Ignore)]
        public long? Index { get; set; }

        [JsonProperty("_Rare", NullValueHandling = NullValueHandling.Ignore)]
        public string Rare { get; set; }

        [JsonProperty("_StoryNo", NullValueHandling = NullValueHandling.Ignore)]
        public string StoryNo { get; set; }

        [JsonProperty("_MaxLevel", NullValueHandling = NullValueHandling.Ignore)]
        public long? MaxLevel { get; set; }

        [JsonProperty("_DefUpValue", NullValueHandling = NullValueHandling.Ignore)]
        public long? DefUpValue { get; set; }

        [JsonProperty("_Point", NullValueHandling = NullValueHandling.Ignore)]
        public long? Point { get; set; }

        [JsonProperty("_Price", NullValueHandling = NullValueHandling.Ignore)]
        public long? Price { get; set; }

        [JsonProperty("_IsSpecialUpgrade", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsSpecialUpgrade { get; set; }
    }

    public partial class ArmorUpgradeDatum
    {
        public static ArmorUpgradeDatum[] FromJson(string json) => JsonConvert.DeserializeObject<ArmorUpgradeDatum[]>(json, MHWildsArmour.Json.ArmorUpgradeConverter.Settings);
    }

    public static partial class Serialize
    {
        public static string ToJson(this ArmorUpgradeDatum[] self) => JsonConvert.SerializeObject(self, MHWildsArmour.Json.ArmorUpgradeConverter.Settings);
    }

    internal static class ArmorUpgradeConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
