// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MHWildsArmour.Json;
//
//    var armorRecipeDatum = ArmorRecipeDatum.FromJson(jsonString);

namespace MHWildsArmour.Json
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ArmorRecipeDatum
    {
        [JsonProperty("_Index", NullValueHandling = NullValueHandling.Ignore)]
        public long? Index { get; set; }

        [JsonProperty("_RecipeNo", NullValueHandling = NullValueHandling.Ignore)]
        public long? RecipeNo { get; set; }

        [JsonProperty("_SeriesId", NullValueHandling = NullValueHandling.Ignore)]
        public string SeriesId { get; set; }

        [JsonProperty("_PartsType", NullValueHandling = NullValueHandling.Ignore)]
        public string PartsType { get; set; }

        [JsonProperty("_KeyItemId", NullValueHandling = NullValueHandling.Ignore)]
        public string KeyItemId { get; set; }

        [JsonProperty("_KeyEnemyId", NullValueHandling = NullValueHandling.Ignore)]
        public string KeyEnemyId { get; set; }

        [JsonProperty("_KeyStoryNo", NullValueHandling = NullValueHandling.Ignore)]
        public string KeyStoryNo { get; set; }

        [JsonProperty("_FlagHunterRank", NullValueHandling = NullValueHandling.Ignore)]
        public long? FlagHunterRank { get; set; }

        [JsonProperty("_Item", NullValueHandling = NullValueHandling.Ignore)]
        public string[] ItemId { get; set; }

        [JsonProperty("_ItemNum", NullValueHandling = NullValueHandling.Ignore)]
        public long[] ItemNum { get; set; }
    }

    public partial class ArmorRecipeDatum
    {
        //public Item[] Item { get; set; }

        public ItemDatum[] Items { get; set; }

        public static ArmorRecipeDatum[] FromJson(string json) => JsonConvert.DeserializeObject<ArmorRecipeDatum[]>(json, MHWildsArmour.Json.ArmorRecipeConverter.Settings);
    }

    public static partial class Serialize
    {
        public static string ToJson(this ArmorRecipeDatum[] self) => JsonConvert.SerializeObject(self, MHWildsArmour.Json.ArmorRecipeConverter.Settings);
    }

    internal static class ArmorRecipeConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
