// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MHWildsArmour.Json;
//
//    var armorDatum = ArmorDatum.FromJson(jsonString);

namespace MHWildsArmour.Json
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ArmorDatum
    {
        [JsonProperty("_Index", NullValueHandling = NullValueHandling.Ignore)]
        public long? Index { get; set; }

        [JsonProperty("_DataValue", NullValueHandling = NullValueHandling.Ignore)]
        public long? DataValue { get; set; }

        [JsonProperty("_Series", NullValueHandling = NullValueHandling.Ignore)]
        public string SeriesId { get; set; }

        [JsonProperty("_PartsType", NullValueHandling = NullValueHandling.Ignore)]
        public string PartsType { get; set; }

        [JsonProperty("_Name", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? NameGuid { get; set; }

        [JsonProperty("_Explain", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? ExplainGuid { get; set; }

        [JsonProperty("_Defense", NullValueHandling = NullValueHandling.Ignore)]
        public long? Defense { get; set; }

        [JsonProperty("_Resistance", NullValueHandling = NullValueHandling.Ignore)]
        public long[] Resistance { get; set; }

        [JsonProperty("_SlotLevel", NullValueHandling = NullValueHandling.Ignore)]
        public string[] SlotLevelString { get; set; }

        [JsonProperty("_Skill", NullValueHandling = NullValueHandling.Ignore)]
        public string[] SkillId { get; set; }

        [JsonProperty("_SkillLevel", NullValueHandling = NullValueHandling.Ignore)]
        public long[] SkillLevel { get; set; }
    }

    public partial class ArmorDatum
    {
        public string Name { get; set; }

        public string Explain { get; set; }

        public int[] SlotLevel { get; set; }

       // public ArmorSkill[] Skill { get; set; }

        public SkillCommonDatum[] SkillCommon { get; set; }

        public ArmorSeriesDatum Series { get; set; }

        public ArmorRecipeDatum Recipe { get; set; }

        public static ArmorDatum[] FromJson(string json) => JsonConvert.DeserializeObject<ArmorDatum[]>(json, MHWildsArmour.Json.ArmorConverter.Settings);
    }

    public static partial class Serialize
    {
        public static string ToJson(this ArmorDatum[] self) => JsonConvert.SerializeObject(self, MHWildsArmour.Json.ArmorConverter.Settings);
    }

    internal static class ArmorConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
            Formatting = Formatting.Indented
        };
    }
}
