// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MHWildsArmour.Json;
//
//    var skillCommonDatum = SkillCommonDatum.FromJson(jsonString);

namespace MHWildsArmour.Json
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SkillCommonDatum
    {
        [JsonProperty("_Index", NullValueHandling = NullValueHandling.Ignore)]
        public long? Index { get; set; }

        [JsonProperty("_skillId", NullValueHandling = NullValueHandling.Ignore)]
        public string SkillId { get; set; }

        [JsonProperty("_skillType", NullValueHandling = NullValueHandling.Ignore)]
        public string SkillType { get; set; }

        [JsonProperty("_skillCategory", NullValueHandling = NullValueHandling.Ignore)]
        public string SkillCategory { get; set; }

        [JsonProperty("_SkillIconType", NullValueHandling = NullValueHandling.Ignore)]
        public string SkillIconType { get; set; }

        [JsonProperty("_skillName", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? SkillNameGuid { get; set; }

        [JsonProperty("_skillExplain", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? SkillExplainGuid { get; set; }

        [JsonProperty("_SortId", NullValueHandling = NullValueHandling.Ignore)]
        public long? SortId { get; set; }
    }

    public partial class SkillCommonDatum
    {
        public string SkillName { get; set; }

        public string SkillExplain { get; set; }

        public string SkillWikiIconFile { get; set; }

        public string SkillIconTypeString { get; set; }

        public static SkillCommonDatum[] FromJson(string json) => JsonConvert.DeserializeObject<SkillCommonDatum[]>(json, MHWildsArmour.Json.SkillCommonConverter.Settings);
    }

    public static partial class Serialize
    {
        public static string ToJson(this SkillCommonDatum[] self) => JsonConvert.SerializeObject(self, MHWildsArmour.Json.SkillCommonConverter.Settings);
    }

    internal static class SkillCommonConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
