// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MHWildsArmour.Json;
//
//    var armorMsg = ArmorMsg.FromJson(jsonString);

namespace MHWildsArmour.Json
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WildsMsg
    {
        [JsonProperty("version", NullValueHandling = NullValueHandling.Ignore)]
        public long? Version { get; set; }

        [JsonProperty("languages", NullValueHandling = NullValueHandling.Ignore)]
        public long[] Languages { get; set; }

        [JsonProperty("attribute_headers", NullValueHandling = NullValueHandling.Ignore)]
        public object[] AttributeHeaders { get; set; }

        [JsonProperty("entries", NullValueHandling = NullValueHandling.Ignore)]
        public Entry[] Entries { get; set; }
    }

    public partial class Entry
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("guid", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? Guid { get; set; }

        [JsonProperty("crc?", NullValueHandling = NullValueHandling.Ignore)]
        public long? Crc { get; set; }

        [JsonProperty("hash", NullValueHandling = NullValueHandling.Ignore)]
        public long? Hash { get; set; }

        [JsonProperty("attributes", NullValueHandling = NullValueHandling.Ignore)]
        public object[] Attributes { get; set; }

        [JsonProperty("content", NullValueHandling = NullValueHandling.Ignore)]
        public string[] Content { get; set; }
    }

    public partial class WildsMsg
    {
        public static WildsMsg FromJson(string json) => JsonConvert.DeserializeObject<WildsMsg>(json, MHWildsArmour.Json.WildsMsgConverter.Settings);
    }

    public static partial class Serialize
    {
        public static string ToJson(this WildsMsg self) => JsonConvert.SerializeObject(self, MHWildsArmour.Json.WildsMsgConverter.Settings);
    }

    internal static class WildsMsgConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
